title: Hello, world! I'm Charles Minderhout
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.charminder.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Charles Minderhout # add your name
author-img: david-freeman.jpg # add your photo
about-author: I am a software engineer working with Rails, Vue, and Angular. Always hungry to keep learning and push myself further. # add description
social-twitter: charlesminderhout # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: charminder # add your Github handle
social-linkedin: charlesminderhout # add your Linkedin handle
social-email: charleswminderhout@outlook.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
